### PR TITLE
Changed gitignore

### PR DESCRIPTION
**Pull request by FHatCSW**
**Description of changes**
changed the path for ignored files from tests/data/issuing_ca/* to tests/data/issuing_cas/*

**Notes** 

**Legal** 
- [x] I certify that I have all necessary rights to publish this contribution under the MIT license. I agree to the Trustpoint CLA and have added my name to the AUTHORS.md file.

### CODE REVIEW

**Comment by AlexHx8472** [comment]
We should include both tests/data/issuing_ca and tests/data/issuing_cas since both exist actually.

**Comment by FHatCSW** [comment]
Oh, I did‘t check this… Will do an update

mit freundlichen Grüßen / Kind regards

i.A. Florian Handke
Leiter Industrial Security

Campus Schwarzwald
Herzog-Eberhard-Straße 56
72250 Freudenstadt

M:  +49 151 553 603 39
E-Mail: ***@***.***
________________________________


--​‍​
	
                  	
Centrum für Digitalisierung, Führung und Nachhaltigkeit Schwarzwald gGmbH | Herzog-Eberhard-Str. 56 | 72250 Freudenstadt | T: +49 7441 86849 00 	
***@***.*** | www.campus-schwarzwald.de | Geschäftsführer: Stefan Bogenrieder | Amtsgericht Stuttgart | HRB 759245 I USt ID DE310457061

Von: AlexHx8472 ***@***.***>
Gesendet: Monday, November 4, 2024 5:22:44 PM
An: TrustPoint-Project/trustpoint ***@***.***>
Cc: Florian Handke ***@***.***>; Author ***@***.***>
Betreff: Re: [TrustPoint-Project/trustpoint] Changed gitignore (PR #150)


We should include both tests/data/issuing_ca and tests/data/issuing_cas since both exist actually.

**Comment by FHatCSW** [comment]
@AlexHx8472: Added tests/data/issuing_ca/* again

**Comment by FHatCSW** [comment]
@AlexHx8472: Added *.p12

**Review by Aircoookie — APPROVED** [review]

**Pull request merged**
