### PR TITLE
Adding a management command to add domains and devices

### PR DESCRIPTION
**Pull request by FHatCSW**
Related to #

**Description of changes**
Adding a new management command for adding devices and domains

**Notes** 

**Legal** 
- [x] I certify that I have all necessary rights to publish this contribution under the MIT license. I agree to the Trustpoint CLA and have added my name to the AUTHORS.md file.

### CODE REVIEW

**Comment by BytesWelder** [comment]
Hi @FHatCSW , there was a circular import error in the serializer, which got fixed with the main merge.
We now load the onboarding_protocols instead of hardcoding, so that when we merge the browser_onboarding it gets automatically added.

Otherwise my question. What is the usecase of this command? Since we don't add an IssuingCA we can not onboard the devices.

**Comment by FHatCSW** [comment]
Hi @BytesWelder,

thanks for the clarification. The main idea was to populate the database with some realistic values of machine devices and domains. Mainly for showcasing stuff. We could randomly assign the available Issuing CAs to the domains to extend this.

**Comment by BytesWelder** [comment]
I would recommend it. So in a showcase situation, if asked we can also demonstrate an onboarding :)

**Comment by AlexHx8472** [comment]
Looks good to me too. I'll merge the pull request.

**Pull request merged**
