### PR TITLE
Dashboard and notification internationalization

### PR DESCRIPTION
**Pull request by Aircoookie**
**Description of changes**
- Adds Home overview translations.

**Note**
- Database Reset is required.

**Legal** 
- [x] I certify that I have all necessary rights to publish this contribution under the MIT license. I agree to the Trustpoint CLA and have added my name to the AUTHORS.md file.

### CODE REVIEW

**Comment by Aircoookie** [comment]
This is now 100% complete and works very well, as notification string building is deferred so translations can be dynamically updated.
The only thing I am not fully satisfied with is that all notification strings are now defined in `NotificationMessageType.get_message()`. I think it's OK for the time being, but if you have an idea how to move the strings back to the place where the `NotificationModel` is initializaed, that would perhaps be preferable.

**Comment by FHatCSW** [comment]
Hi @Aircoookie 
I tested your changes but could not get it working. After setting the language to German I would expect the Notifications which were already created and the new ones also in German.

**Comment by Aircoookie** [comment]
Hi @FHatCSW , did you apply migrations and reset the database? Existing notifications (implemented as "Custom" type here) will not translate, but all notifications using the system herein will dynamically translate correctly even after they were created.

**Comment by FHatCSW** [comment]
Looks good to me 👌

**Review by FHatCSW — APPROVED** [review]

**Pull request merged**
